;;; cl-gsl/gsl.lisp

(cl:in-package "GSL")

;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.10
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.


(cffi:defctype size_t :unsigned-int)

(cffi:defcstruct gsl_vector
	(size :unsigned-int)
	(stride :unsigned-int)
	(data :pointer)
	(block :pointer)
	(owner :int))

(cffi:defcstruct gsl_vector_float
	(size :unsigned-int)
	(stride :unsigned-int)
	(data :pointer)
	(block :pointer)
	(owner :int))

(cffi:defcfun ("gsl_vector_alloc" gsl_vector_alloc) :pointer
  (n :unsigned-int))

(cffi:defcfun ("gsl_vector_calloc" gsl_vector_calloc) :pointer
  (n :unsigned-int))

(cffi:defcfun ("gsl_vector_free" gsl_vector_free) :void
  (v :pointer))

(cffi:defcfun ("gsl_vector_float_alloc" gsl_vector_float_alloc) :pointer
  (n :unsigned-int))

(cffi:defcfun ("gsl_vector_float_calloc" gsl_vector_float_calloc) :pointer
  (n :unsigned-int))

(cffi:defcfun ("gsl_vector_float_free" gsl_vector_float_free) :void
  (v :pointer))

(cffi:defcfun ("gsl_vector_set_zero" gsl_vector_set_zero) :void
  (v :pointer))

(cffi:defcfun ("gsl_vector_set_all" gsl_vector_set_all) :void
  (v :pointer)
  (x :double))

(cffi:defcfun ("gsl_vector_set_basis" gsl_vector_set_basis) :int
  (v :pointer)
  (i :unsigned-int))

(cffi:defcfun ("gsl_vector_memcpy" gsl_vector_memcpy) :int
  (dest :pointer)
  (src :pointer))

(cffi:defcfun ("gsl_vector_reverse" gsl_vector_reverse) :int
  (v :pointer))

(cffi:defcfun ("gsl_vector_swap" gsl_vector_swap) :int
  (v :pointer)
  (w :pointer))

(cffi:defcfun ("gsl_vector_swap_elements" gsl_vector_swap_elements) :int
  (v :pointer)
  (i :unsigned-int)
  (j :unsigned-int))

(cffi:defcfun ("gsl_vector_max" gsl_vector_max) :double
  (v :pointer))

(cffi:defcfun ("gsl_vector_min" gsl_vector_min) :double
  (v :pointer))

(cffi:defcfun ("gsl_vector_minmax" gsl_vector_minmax) :void
  (v :pointer)
  (min_out :pointer)
  (max_out :pointer))

(cffi:defcfun ("gsl_vector_max_index" gsl_vector_max_index) :unsigned-int
  (v :pointer))

(cffi:defcfun ("gsl_vector_min_index" gsl_vector_min_index) :unsigned-int
  (v :pointer))

(cffi:defcfun ("gsl_vector_minmax_index" gsl_vector_minmax_index) :void
  (v :pointer)
  (imin :pointer)
  (imax :pointer))

(cffi:defcfun ("gsl_vector_add" gsl_vector_add) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_vector_sub" gsl_vector_sub) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_vector_mul" gsl_vector_mul) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_vector_div" gsl_vector_div) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_vector_scale" gsl_vector_scale) :int
  (a :pointer)
  (x :double))

(cffi:defcfun ("gsl_vector_add_constant" gsl_vector_add_constant) :int
  (a :pointer)
  (x :double))

(cffi:defcfun ("gsl_vector_equal" gsl_vector_equal) :int
  (u :pointer)
  (v :pointer))

(cffi:defcfun ("gsl_vector_isnull" gsl_vector_isnull) :int
  (v :pointer))

(cffi:defcfun ("gsl_vector_ispos" gsl_vector_ispos) :int
  (v :pointer))

(cffi:defcfun ("gsl_vector_isneg" gsl_vector_isneg) :int
  (v :pointer))

(cffi:defcfun ("gsl_vector_isnonneg" gsl_vector_isnonneg) :int
  (v :pointer))

(cffi:defcfun ("gsl_vector_get" gsl_vector_get) :double
  (v :pointer)
  (i :unsigned-int))

(cffi:defcfun ("gsl_vector_set" gsl_vector_set) :void
  (v :pointer)
  (i :unsigned-int)
  (x :double))

(cffi:defcfun ("gsl_vector_ptr" gsl_vector_ptr) :pointer
  (v :pointer)
  (i :unsigned-int))

(cffi:defcfun ("gsl_vector_const_ptr" gsl_vector_const_ptr) :pointer
  (v :pointer)
  (i :unsigned-int))

(cffi:defcfun ("gsl_vector_float_set_zero" gsl_vector_float_set_zero) :void
  (v :pointer))

(cffi:defcfun ("gsl_vector_float_set_all" gsl_vector_float_set_all) :void
  (v :pointer)
  (x :float))

(cffi:defcfun ("gsl_vector_float_set_basis" gsl_vector_float_set_basis) :int
  (v :pointer)
  (i :unsigned-int))

(cffi:defcfun ("gsl_vector_float_memcpy" gsl_vector_float_memcpy) :int
  (dest :pointer)
  (src :pointer))

(cffi:defcfun ("gsl_vector_float_reverse" gsl_vector_float_reverse) :int
  (v :pointer))

(cffi:defcfun ("gsl_vector_float_swap" gsl_vector_float_swap) :int
  (v :pointer)
  (w :pointer))

(cffi:defcfun ("gsl_vector_float_swap_elements" gsl_vector_float_swap_elements) :int
  (v :pointer)
  (i :unsigned-int)
  (j :unsigned-int))

(cffi:defcfun ("gsl_vector_float_max" gsl_vector_float_max) :float
  (v :pointer))

(cffi:defcfun ("gsl_vector_float_min" gsl_vector_float_min) :float
  (v :pointer))

(cffi:defcfun ("gsl_vector_float_minmax" gsl_vector_float_minmax) :void
  (v :pointer)
  (min_out :pointer)
  (max_out :pointer))

(cffi:defcfun ("gsl_vector_float_max_index" gsl_vector_float_max_index) :unsigned-int
  (v :pointer))

(cffi:defcfun ("gsl_vector_float_min_index" gsl_vector_float_min_index) :unsigned-int
  (v :pointer))

(cffi:defcfun ("gsl_vector_float_minmax_index" gsl_vector_float_minmax_index) :void
  (v :pointer)
  (imin :pointer)
  (imax :pointer))

(cffi:defcfun ("gsl_vector_float_add" gsl_vector_float_add) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_vector_float_sub" gsl_vector_float_sub) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_vector_float_mul" gsl_vector_float_mul) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_vector_float_div" gsl_vector_float_div) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_vector_float_scale" gsl_vector_float_scale) :int
  (a :pointer)
  (x :double))

(cffi:defcfun ("gsl_vector_float_add_constant" gsl_vector_float_add_constant) :int
  (a :pointer)
  (x :double))

(cffi:defcfun ("gsl_vector_float_equal" gsl_vector_float_equal) :int
  (u :pointer)
  (v :pointer))

(cffi:defcfun ("gsl_vector_float_isnull" gsl_vector_float_isnull) :int
  (v :pointer))

(cffi:defcfun ("gsl_vector_float_ispos" gsl_vector_float_ispos) :int
  (v :pointer))

(cffi:defcfun ("gsl_vector_float_isneg" gsl_vector_float_isneg) :int
  (v :pointer))

(cffi:defcfun ("gsl_vector_float_isnonneg" gsl_vector_float_isnonneg) :int
  (v :pointer))

(cffi:defcfun ("gsl_vector_float_get" gsl_vector_float_get) :float
  (v :pointer)
  (i :unsigned-int))

(cffi:defcfun ("gsl_vector_float_set" gsl_vector_float_set) :void
  (v :pointer)
  (i :unsigned-int)
  (x :float))

(cffi:defcfun ("gsl_vector_float_ptr" gsl_vector_float_ptr) :pointer
  (v :pointer)
  (i :unsigned-int))

(cffi:defcfun ("gsl_vector_float_const_ptr" gsl_vector_float_const_ptr) :pointer
  (v :pointer)
  (i :unsigned-int))


