;;; cl-gsl/gsl.lisp

(cl:in-package "GSL")

;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.10
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.


(cffi:defctype size_t :unsigned-int)

(cffi:defcstruct gsl_qrng_type
	(name :string)
	(max_dimension :unsigned-int)
	(state_size :pointer)
	(init_state :pointer)
	(get :pointer))

(cffi:defcstruct gsl_qrng
	(type :pointer)
	(dimension :unsigned-int)
	(state_size :unsigned-int)
	(state :pointer))

(cffi:defcvar ("gsl_qrng_niederreiter_2" gsl_qrng_niederreiter_2)
 :pointer)

(cffi:defcvar ("gsl_qrng_sobol" gsl_qrng_sobol)
 :pointer)

(cffi:defcvar ("gsl_qrng_halton" gsl_qrng_halton)
 :pointer)

(cffi:defcvar ("gsl_qrng_reversehalton" gsl_qrng_reversehalton)
 :pointer)

(cffi:defcfun ("gsl_qrng_alloc" gsl_qrng_alloc) :pointer
  (t_arg0 :pointer)
  (dimension :unsigned-int))

(cffi:defcfun ("gsl_qrng_memcpy" gsl_qrng_memcpy) :int
  (dest :pointer)
  (src :pointer))

(cffi:defcfun ("gsl_qrng_clone" gsl_qrng_clone) :pointer
  (q :pointer))

(cffi:defcfun ("gsl_qrng_free" gsl_qrng_free) :void
  (q :pointer))

(cffi:defcfun ("gsl_qrng_init" gsl_qrng_init) :void
  (q :pointer))

(cffi:defcfun ("gsl_qrng_name" gsl_qrng_name) :string
  (q :pointer))

(cffi:defcfun ("gsl_qrng_size" gsl_qrng_size) :unsigned-int
  (q :pointer))

(cffi:defcfun ("gsl_qrng_state" gsl_qrng_state) :pointer
  (q :pointer))

(cffi:defcfun ("gsl_qrng_get" gsl_qrng_get) :int
  (q :pointer)
  (x :pointer))


