;;; cl-gsl/gsl.lisp

(cl:in-package "GSL")

;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.10
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.


(cffi:defctype size_t :unsigned-int)

(cffi:defcstruct gsl_matrix
	(size1 :unsigned-int)
	(size2 :unsigned-int)
	(tda :unsigned-int)
	(data :pointer)
	(block :pointer)
	(owner :int))

(cffi:defcstruct gsl_matrix_float
	(size1 :unsigned-int)
	(size2 :unsigned-int)
	(tda :unsigned-int)
	(data :pointer)
	(block :pointer)
	(owner :int))

(cffi:defcfun ("gsl_matrix_alloc" gsl_matrix_alloc) :pointer
  (n1 :unsigned-int)
  (n2 :unsigned-int))

(cffi:defcfun ("gsl_matrix_calloc" gsl_matrix_calloc) :pointer
  (n1 :unsigned-int)
  (n2 :unsigned-int))

(cffi:defcfun ("gsl_matrix_free" gsl_matrix_free) :void
  (m :pointer))

(cffi:defcfun ("gsl_matrix_float_alloc" gsl_matrix_float_alloc) :pointer
  (n1 :unsigned-int)
  (n2 :unsigned-int))

(cffi:defcfun ("gsl_matrix_float_calloc" gsl_matrix_float_calloc) :pointer
  (n1 :unsigned-int)
  (n2 :unsigned-int))

(cffi:defcfun ("gsl_matrix_float_free" gsl_matrix_float_free) :void
  (m :pointer))

(cffi:defcfun ("gsl_matrix_set_zero" gsl_matrix_set_zero) :void
  (m :pointer))

(cffi:defcfun ("gsl_matrix_set_identity" gsl_matrix_set_identity) :void
  (m :pointer))

(cffi:defcfun ("gsl_matrix_set_all" gsl_matrix_set_all) :void
  (m :pointer)
  (x :double))

(cffi:defcfun ("gsl_matrix_memcpy" gsl_matrix_memcpy) :int
  (dest :pointer)
  (src :pointer))

(cffi:defcfun ("gsl_matrix_swap" gsl_matrix_swap) :int
  (m1 :pointer)
  (m2 :pointer))

(cffi:defcfun ("gsl_matrix_swap_rows" gsl_matrix_swap_rows) :int
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int))

(cffi:defcfun ("gsl_matrix_swap_columns" gsl_matrix_swap_columns) :int
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int))

(cffi:defcfun ("gsl_matrix_swap_rowcol" gsl_matrix_swap_rowcol) :int
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int))

(cffi:defcfun ("gsl_matrix_transpose" gsl_matrix_transpose) :int
  (m :pointer))

(cffi:defcfun ("gsl_matrix_transpose_memcpy" gsl_matrix_transpose_memcpy) :int
  (dest :pointer)
  (src :pointer))

(cffi:defcfun ("gsl_matrix_max" gsl_matrix_max) :double
  (m :pointer))

(cffi:defcfun ("gsl_matrix_min" gsl_matrix_min) :double
  (m :pointer))

(cffi:defcfun ("gsl_matrix_minmax" gsl_matrix_minmax) :void
  (m :pointer)
  (min_out :pointer)
  (max_out :pointer))

(cffi:defcfun ("gsl_matrix_max_index" gsl_matrix_max_index) :void
  (m :pointer)
  (imax :pointer)
  (jmax :pointer))

(cffi:defcfun ("gsl_matrix_min_index" gsl_matrix_min_index) :void
  (m :pointer)
  (imin :pointer)
  (jmin :pointer))

(cffi:defcfun ("gsl_matrix_minmax_index" gsl_matrix_minmax_index) :void
  (m :pointer)
  (imin :pointer)
  (jmin :pointer)
  (imax :pointer)
  (jmax :pointer))

(cffi:defcfun ("gsl_matrix_equal" gsl_matrix_equal) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_matrix_isnull" gsl_matrix_isnull) :int
  (m :pointer))

(cffi:defcfun ("gsl_matrix_ispos" gsl_matrix_ispos) :int
  (m :pointer))

(cffi:defcfun ("gsl_matrix_isneg" gsl_matrix_isneg) :int
  (m :pointer))

(cffi:defcfun ("gsl_matrix_isnonneg" gsl_matrix_isnonneg) :int
  (m :pointer))

(cffi:defcfun ("gsl_matrix_add" gsl_matrix_add) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_matrix_sub" gsl_matrix_sub) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_matrix_mul_elements" gsl_matrix_mul_elements) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_matrix_div_elements" gsl_matrix_div_elements) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_matrix_scale" gsl_matrix_scale) :int
  (a :pointer)
  (x :double))

(cffi:defcfun ("gsl_matrix_add_constant" gsl_matrix_add_constant) :int
  (a :pointer)
  (x :double))

(cffi:defcfun ("gsl_matrix_add_diagonal" gsl_matrix_add_diagonal) :int
  (a :pointer)
  (x :double))

(cffi:defcfun ("gsl_matrix_get_row" gsl_matrix_get_row) :int
  (v :pointer)
  (m :pointer)
  (i :unsigned-int))

(cffi:defcfun ("gsl_matrix_get_col" gsl_matrix_get_col) :int
  (v :pointer)
  (m :pointer)
  (j :unsigned-int))

(cffi:defcfun ("gsl_matrix_set_row" gsl_matrix_set_row) :int
  (m :pointer)
  (i :unsigned-int)
  (v :pointer))

(cffi:defcfun ("gsl_matrix_set_col" gsl_matrix_set_col) :int
  (m :pointer)
  (j :unsigned-int)
  (v :pointer))

(cffi:defcfun ("gsl_matrix_get" gsl_matrix_get) :double
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int))

(cffi:defcfun ("gsl_matrix_set" gsl_matrix_set) :void
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int)
  (x :double))

(cffi:defcfun ("gsl_matrix_ptr" gsl_matrix_ptr) :pointer
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int))

(cffi:defcfun ("gsl_matrix_const_ptr" gsl_matrix_const_ptr) :pointer
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int))

(cffi:defcfun ("gsl_matrix_float_set_zero" gsl_matrix_float_set_zero) :void
  (m :pointer))

(cffi:defcfun ("gsl_matrix_float_set_identity" gsl_matrix_float_set_identity) :void
  (m :pointer))

(cffi:defcfun ("gsl_matrix_float_set_all" gsl_matrix_float_set_all) :void
  (m :pointer)
  (x :float))

(cffi:defcfun ("gsl_matrix_float_memcpy" gsl_matrix_float_memcpy) :int
  (dest :pointer)
  (src :pointer))

(cffi:defcfun ("gsl_matrix_float_swap" gsl_matrix_float_swap) :int
  (m1 :pointer)
  (m2 :pointer))

(cffi:defcfun ("gsl_matrix_float_swap_rows" gsl_matrix_float_swap_rows) :int
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int))

(cffi:defcfun ("gsl_matrix_float_swap_columns" gsl_matrix_float_swap_columns) :int
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int))

(cffi:defcfun ("gsl_matrix_float_swap_rowcol" gsl_matrix_float_swap_rowcol) :int
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int))

(cffi:defcfun ("gsl_matrix_float_transpose" gsl_matrix_float_transpose) :int
  (m :pointer))

(cffi:defcfun ("gsl_matrix_float_transpose_memcpy" gsl_matrix_float_transpose_memcpy) :int
  (dest :pointer)
  (src :pointer))

(cffi:defcfun ("gsl_matrix_float_max" gsl_matrix_float_max) :float
  (m :pointer))

(cffi:defcfun ("gsl_matrix_float_min" gsl_matrix_float_min) :float
  (m :pointer))

(cffi:defcfun ("gsl_matrix_float_minmax" gsl_matrix_float_minmax) :void
  (m :pointer)
  (min_out :pointer)
  (max_out :pointer))

(cffi:defcfun ("gsl_matrix_float_max_index" gsl_matrix_float_max_index) :void
  (m :pointer)
  (imax :pointer)
  (jmax :pointer))

(cffi:defcfun ("gsl_matrix_float_min_index" gsl_matrix_float_min_index) :void
  (m :pointer)
  (imin :pointer)
  (jmin :pointer))

(cffi:defcfun ("gsl_matrix_float_minmax_index" gsl_matrix_float_minmax_index) :void
  (m :pointer)
  (imin :pointer)
  (jmin :pointer)
  (imax :pointer)
  (jmax :pointer))

(cffi:defcfun ("gsl_matrix_float_equal" gsl_matrix_float_equal) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_matrix_float_isnull" gsl_matrix_float_isnull) :int
  (m :pointer))

(cffi:defcfun ("gsl_matrix_float_ispos" gsl_matrix_float_ispos) :int
  (m :pointer))

(cffi:defcfun ("gsl_matrix_float_isneg" gsl_matrix_float_isneg) :int
  (m :pointer))

(cffi:defcfun ("gsl_matrix_float_isnonneg" gsl_matrix_float_isnonneg) :int
  (m :pointer))

(cffi:defcfun ("gsl_matrix_float_add" gsl_matrix_float_add) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_matrix_float_sub" gsl_matrix_float_sub) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_matrix_float_mul_elements" gsl_matrix_float_mul_elements) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_matrix_float_div_elements" gsl_matrix_float_div_elements) :int
  (a :pointer)
  (b :pointer))

(cffi:defcfun ("gsl_matrix_float_scale" gsl_matrix_float_scale) :int
  (a :pointer)
  (x :double))

(cffi:defcfun ("gsl_matrix_float_add_constant" gsl_matrix_float_add_constant) :int
  (a :pointer)
  (x :double))

(cffi:defcfun ("gsl_matrix_float_add_diagonal" gsl_matrix_float_add_diagonal) :int
  (a :pointer)
  (x :double))

(cffi:defcfun ("gsl_matrix_float_get_row" gsl_matrix_float_get_row) :int
  (v :pointer)
  (m :pointer)
  (i :unsigned-int))

(cffi:defcfun ("gsl_matrix_float_get_col" gsl_matrix_float_get_col) :int
  (v :pointer)
  (m :pointer)
  (j :unsigned-int))

(cffi:defcfun ("gsl_matrix_float_set_row" gsl_matrix_float_set_row) :int
  (m :pointer)
  (i :unsigned-int)
  (v :pointer))

(cffi:defcfun ("gsl_matrix_float_set_col" gsl_matrix_float_set_col) :int
  (m :pointer)
  (j :unsigned-int)
  (v :pointer))

(cffi:defcfun ("gsl_matrix_float_get" gsl_matrix_float_get) :float
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int))

(cffi:defcfun ("gsl_matrix_float_set" gsl_matrix_float_set) :void
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int)
  (x :float))

(cffi:defcfun ("gsl_matrix_float_ptr" gsl_matrix_float_ptr) :pointer
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int))

(cffi:defcfun ("gsl_matrix_float_const_ptr" gsl_matrix_float_const_ptr) :pointer
  (m :pointer)
  (i :unsigned-int)
  (j :unsigned-int))


