;;; cl-gsl/gsl.lisp

(cl:in-package "GSL")

;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.12
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.


(cffi:defctype size_t :unsigned-int)

(cffi:defcstruct gsl_histogram
	(n :unsigned-int)
	(range :pointer)
	(bin :pointer))

(cffi:defcstruct gsl_histogram_pdf
	(n :unsigned-int)
	(range :pointer)
	(sum :pointer))

(cffi:defcfun ("gsl_histogram_alloc" gsl_histogram_alloc) :pointer
  (n :unsigned-int))

(cffi:defcfun ("gsl_histogram_set_ranges" gsl_histogram_set_ranges) :int
  (h :pointer)
  (range :pointer)
  (size :unsigned-int))

(cffi:defcfun ("gsl_histogram_set_ranges_uniform" gsl_histogram_set_ranges_uniform) :int
  (h :pointer)
  (xmin :double)
  (xmax :double))

(cffi:defcfun ("gsl_histogram_free" gsl_histogram_free) :void
  (h :pointer))

(cffi:defcfun ("gsl_histogram_memcpy" gsl_histogram_memcpy) :int
  (dest :pointer)
  (source :pointer))

(cffi:defcfun ("gsl_histogram_clone" gsl_histogram_clone) :pointer
  (source :pointer))

(cffi:defcfun ("gsl_histogram_increment" gsl_histogram_increment) :int
  (h :pointer)
  (x :double))

(cffi:defcfun ("gsl_histogram_accumulate" gsl_histogram_accumulate) :int
  (h :pointer)
  (x :double)
  (weight :double))

(cffi:defcfun ("gsl_histogram_get" gsl_histogram_get) :double
  (h :pointer)
  (i :unsigned-int))

(cffi:defcfun ("gsl_histogram_get_range" gsl_histogram_get_range) :int
  (h :pointer)
  (i :unsigned-int)
  (lower :pointer)
  (upper :pointer))

(cffi:defcfun ("gsl_histogram_max" gsl_histogram_max) :double
  (h :pointer))

(cffi:defcfun ("gsl_histogram_min" gsl_histogram_min) :double
  (h :pointer))

(cffi:defcfun ("gsl_histogram_bins" gsl_histogram_bins) :unsigned-int
  (h :pointer))

(cffi:defcfun ("gsl_histogram_reset" gsl_histogram_reset) :void
  (h :pointer))

(cffi:defcfun ("gsl_histogram_find" gsl_histogram_find) :int
  (h :pointer)
  (x :double)
  (i :pointer))

(cffi:defcfun ("gsl_histogram_max_val" gsl_histogram_max_val) :double
  (h :pointer))

(cffi:defcfun ("gsl_histogram_max_bin" gsl_histogram_max_bin) :unsigned-int
  (h :pointer))

(cffi:defcfun ("gsl_histogram_min_val" gsl_histogram_min_val) :double
  (h :pointer))

(cffi:defcfun ("gsl_histogram_min_bin" gsl_histogram_min_bin) :unsigned-int
  (h :pointer))

(cffi:defcfun ("gsl_histogram_mean" gsl_histogram_mean) :double
  (h :pointer))

(cffi:defcfun ("gsl_histogram_sigma" gsl_histogram_sigma) :double
  (h :pointer))

(cffi:defcfun ("gsl_histogram_sum" gsl_histogram_sum) :double
  (h :pointer))

(cffi:defcfun ("gsl_histogram_equal_bins_p" gsl_histogram_equal_bins_p) :int
  (h1 :pointer)
  (h2 :pointer))

(cffi:defcfun ("gsl_histogram_add" gsl_histogram_add) :int
  (h1 :pointer)
  (h2 :pointer))

(cffi:defcfun ("gsl_histogram_sub" gsl_histogram_sub) :int
  (h1 :pointer)
  (h2 :pointer))

(cffi:defcfun ("gsl_histogram_mul" gsl_histogram_mul) :int
  (h1 :pointer)
  (h2 :pointer))

(cffi:defcfun ("gsl_histogram_div" gsl_histogram_div) :int
  (h1 :pointer)
  (h2 :pointer))

(cffi:defcfun ("gsl_histogram_scale" gsl_histogram_scale) :int
  (h :pointer)
  (scale :double))

(cffi:defcfun ("gsl_histogram_shift" gsl_histogram_shift) :int
  (h :pointer)
  (shift :double))

(cffi:defcfun ("gsl_histogram_pdf_alloc" gsl_histogram_pdf_alloc) :pointer
  (n :unsigned-int))

(cffi:defcfun ("gsl_histogram_pdf_init" gsl_histogram_pdf_init) :int
  (p :pointer)
  (h :pointer))

(cffi:defcfun ("gsl_histogram_pdf_free" gsl_histogram_pdf_free) :void
  (p :pointer))

(cffi:defcfun ("gsl_histogram_pdf_sample" gsl_histogram_pdf_sample) :double
  (p :pointer)
  (r :double))


